import type { Crop } from '../model/types';

export const SEED_CROPS: Crop[] = [
  {
    id: 'crop-wheat',
    name: 'Пшеница',
    category: 'grain',
    status: 'sowing_now',
    averageYield: 4.2,
    yieldUnit: 't/ha',
    sowingWindow: { start: '25.04', end: '15.05' },
    preferredSoil: 'Чернозём',
    marginPotential: 'high',
    lastSeasonResult: { yield: 4.1, trend: [3.6, 3.8, 3.7, 4.0, 4.1] },
    icon: 'wheat',
  },
  {
    id: 'crop-barley',
    name: 'Ячмень',
    category: 'grain',
    status: 'planned',
    averageYield: 3.8,
    yieldUnit: 't/ha',
    sowingWindow: { start: '20.04', end: '10.05' },
    preferredSoil: 'Каштановая',
    marginPotential: 'medium',
    lastSeasonResult: { yield: 3.6, trend: [3.4, 3.5, 3.3, 3.7, 3.6] },
    icon: 'barley',
  },
  {
    id: 'crop-corn',
    name: 'Кукуруза',
    category: 'grain',
    status: 'sowing_now',
    averageYield: 6.5,
    yieldUnit: 't/ha',
    sowingWindow: { start: '05.05', end: '25.05' },
    preferredSoil: 'Чернозём',
    marginPotential: 'high',
    lastSeasonResult: { yield: 6.2, trend: [5.4, 5.8, 6.0, 5.9, 6.2] },
    icon: 'corn',
  },
  {
    id: 'crop-oat',
    name: 'Овёс',
    category: 'grain',
    status: 'history',
    averageYield: 2.9,
    yieldUnit: 't/ha',
    sowingWindow: { start: '15.04', end: '05.05' },
    preferredSoil: 'Серая лесная',
    marginPotential: 'low',
    lastSeasonResult: { yield: 2.7, trend: [3.1, 2.9, 2.8, 2.6, 2.7] },
    icon: 'wheat',
  },
  {
    id: 'crop-sunflower',
    name: 'Подсолнечник',
    category: 'oilseed',
    status: 'planned',
    averageYield: 2.4,
    yieldUnit: 't/ha',
    sowingWindow: { start: '20.04', end: '15.05' },
    preferredSoil: 'Чернозём',
    marginPotential: 'high',
    lastSeasonResult: { yield: 2.3, trend: [2.0, 2.1, 2.2, 2.1, 2.3] },
    icon: 'sunflower',
  },
  {
    id: 'crop-rapeseed',
    name: 'Рапс',
    category: 'oilseed',
    status: 'history',
    averageYield: 2.1,
    yieldUnit: 't/ha',
    sowingWindow: { start: '15.08', end: '10.09' },
    preferredSoil: 'Суглинок',
    marginPotential: 'medium',
    lastSeasonResult: { yield: 1.9, trend: [2.2, 2.0, 1.8, 2.0, 1.9] },
    icon: 'rapeseed',
  },
  {
    id: 'crop-soy',
    name: 'Соя',
    category: 'oilseed',
    status: 'planned',
    averageYield: 2.2,
    yieldUnit: 't/ha',
    sowingWindow: { start: '10.05', end: '01.06' },
    preferredSoil: 'Чернозём',
    marginPotential: 'high',
    lastSeasonResult: { yield: 2.0, trend: [1.7, 1.8, 1.9, 2.1, 2.0] },
    icon: 'soy',
  },
  {
    id: 'crop-pea',
    name: 'Горох',
    category: 'legume',
    status: 'sowing_now',
    averageYield: 2.8,
    yieldUnit: 't/ha',
    sowingWindow: { start: '10.04', end: '30.04' },
    preferredSoil: 'Каштановая',
    marginPotential: 'medium',
    lastSeasonResult: { yield: 2.6, trend: [2.4, 2.5, 2.3, 2.7, 2.6] },
    icon: 'pea',
  },
  {
    id: 'crop-chickpea',
    name: 'Нут',
    category: 'legume',
    status: 'planned',
    averageYield: 1.8,
    yieldUnit: 't/ha',
    sowingWindow: { start: '20.04', end: '10.05' },
    preferredSoil: 'Каштановая',
    marginPotential: 'medium',
    lastSeasonResult: { yield: 1.6, trend: [1.4, 1.5, 1.5, 1.7, 1.6] },
    icon: 'pea',
  },
];
