import type { Material } from '../model/types';

export const SEED_MATERIALS: Material[] = [
  {
    id: 'mat-wheat-seed',
    name: 'Семена пшеницы озимой',
    note: 'Гром',
    category: 'seeds',
    unit: 'kg',
    pricePerUnit: 42,
    status: 'active',
  },
  {
    id: 'mat-sunflower-seed',
    name: 'Семена подсолнечника',
    note: 'Сумико',
    category: 'seeds',
    unit: 'se',
    pricePerUnit: 18_500,
    status: 'active',
  },
  {
    id: 'mat-an',
    name: 'Аммиачная селитра',
    note: 'N 34,4%',
    category: 'fertilizer',
    unit: 't',
    pricePerUnit: 28_400,
    status: 'active',
  },
  {
    id: 'mat-npk',
    name: 'NPK 16:16:16',
    category: 'fertilizer',
    unit: 't',
    pricePerUnit: 41_200,
    status: 'active',
  },
  {
    id: 'mat-glyphosate',
    name: 'Глифосат',
    note: '360 г/л',
    category: 'ppp',
    unit: 'l',
    pricePerUnit: 890,
    status: 'active',
  },
  {
    id: 'mat-fungicide',
    name: 'Пропиконазол',
    category: 'ppp',
    unit: 'l',
    pricePerUnit: 2_450,
    status: 'active',
  },
  {
    id: 'mat-diesel',
    name: 'Дизельное топливо',
    category: 'fuel',
    unit: 'l',
    pricePerUnit: 71,
    status: 'active',
  },
  {
    id: 'mat-oil',
    name: 'Моторное масло',
    note: 'Не используется в этом сезоне',
    category: 'fuel',
    unit: 'l',
    pricePerUnit: 420,
    status: 'inactive',
  },
];
