import { CURRENT_USER } from '../model/currentUser';
import type { CalculationPlan, PlanAuthor } from '../model/types';

const ANALYST: PlanAuthor = {
  id: 'user-igor',
  name: 'Игорь Белов',
  role: 'Аналитик',
};

const AGRONOMIST: PlanAuthor = {
  id: 'user-maria',
  name: 'Мария Орлова',
  role: 'Агроном',
};

export const SEED_PLANS: CalculationPlan[] = [
  {
    id: 'plan-south-2026',
    name: 'Оптимизация Юг-2026',
    description: 'Севооборот южного кластера на сезон',
    goal: 'maximize_margin',
    status: 'calculating',
    createdBy: CURRENT_USER,
    createdAt: '2026-08-15T08:14:00',
    fieldIds: ['field-1', 'field-2', 'field-5', 'field-12'],
    fieldsCount: 4,
    totalArea: 2153.3,
    crops: ['Пшеница', 'Кукуруза', 'Подсолнечник'],
    constraints: { budgetLimit: 18_000_000, marginDeviationPercent: 12, minAreaPerCrop: 80, maxAreaPerCrop: 900 },
    logs: [
      { timestamp: '2026-08-15T08:14:10', message: 'Инициализация расчёта' },
      { timestamp: '2026-08-15T08:14:12', message: 'Загрузка характеристик полей' },
    ],
  },
  {
    id: 'plan-north',
    name: 'Севооборот Север',
    description: 'Баланс бобовых и зерновых на севере',
    goal: 'maximize_margin',
    status: 'completed',
    createdBy: ANALYST,
    createdAt: '2026-08-10T11:05:00',
    durationSeconds: 754,
    fieldIds: ['field-north-2', 'field-2', 'field-7'],
    fieldsCount: 3,
    totalArea: 1173.3,
    crops: ['Пшеница', 'Горох', 'Соя'],
    constraints: { budgetLimit: 9_500_000, marginDeviationPercent: 8, minAreaPerCrop: 50 },
    logs: [
      { timestamp: '2026-08-10T11:05:08', message: 'Инициализация расчёта' },
      { timestamp: '2026-08-10T11:06:20', message: 'Оптимизация распределения культур' },
      { timestamp: '2026-08-10T11:17:42', message: 'Расчёт завершён' },
    ],
  },
  {
    id: 'plan-oilseed-draft',
    name: 'Черновик масличных',
    description: 'Подсолнечник и рапс на свободных полях',
    goal: 'maximize_margin',
    status: 'draft',
    createdBy: CURRENT_USER,
    createdAt: '2026-08-13T16:40:00',
    fieldIds: ['field-8', 'field-5'],
    fieldsCount: 2,
    totalArea: 1509.1,
    crops: ['Подсолнечник', 'Рапс'],
    constraints: { budgetLimit: 7_200_000 },
    logs: [],
  },
  {
    id: 'plan-error',
    name: 'Кукуруза центр',
    description: 'Пилотный расчёт с жёстким лимитом бюджета',
    goal: 'maximize_margin',
    status: 'error',
    createdBy: ANALYST,
    createdAt: '2026-08-08T09:18:00',
    fieldIds: ['field-3', 'field-7'],
    fieldsCount: 2,
    totalArea: 503.9,
    crops: ['Кукуруза'],
    constraints: { budgetLimit: 800_000, maxAreaPerCrop: 200 },
    logs: [
      { timestamp: '2026-08-08T09:18:12', message: 'Инициализация расчёта' },
      { timestamp: '2026-08-08T09:18:40', message: 'Недостаточно бюджета для выбранных ограничений' },
    ],
  },
  {
    id: 'plan-corn-2025',
    name: 'Кукуруза 2025',
    description: 'Итоговый план прошлого сезона',
    goal: 'maximize_margin',
    status: 'completed',
    createdBy: CURRENT_USER,
    createdAt: '2025-11-02T10:00:00',
    durationSeconds: 512,
    fieldIds: ['field-1', 'field-12'],
    fieldsCount: 2,
    totalArea: 1148.4,
    crops: ['Кукуруза', 'Пшеница'],
    constraints: { budgetLimit: 11_000_000, marginDeviationPercent: 10 },
    logs: [{ timestamp: '2025-11-02T10:08:32', message: 'Расчёт завершён' }],
  },
  {
    id: 'plan-july-south',
    name: 'Июльский прогон Юг',
    description: 'Первая волна оптимизации июля',
    goal: 'maximize_margin',
    status: 'completed',
    createdBy: AGRONOMIST,
    createdAt: '2026-07-20T09:10:00',
    durationSeconds: 640,
    fieldIds: ['field-1', 'field-5'],
    fieldsCount: 2,
    totalArea: 1131.2,
    crops: ['Пшеница', 'Подсолнечник'],
    constraints: { budgetLimit: 8_400_000 },
    logs: [{ timestamp: '2026-07-20T09:20:40', message: 'Расчёт завершён' }],
  },
  {
    id: 'plan-july-north',
    name: 'Север конец июля',
    goal: 'maximize_margin',
    status: 'completed',
    createdBy: ANALYST,
    createdAt: '2026-07-25T14:00:00',
    durationSeconds: 488,
    fieldIds: ['field-north-2', 'field-2'],
    fieldsCount: 2,
    totalArea: 741.8,
    crops: ['Ячмень', 'Горох'],
    constraints: { marginDeviationPercent: 9 },
    logs: [{ timestamp: '2026-07-25T14:08:08', message: 'Расчёт завершён' }],
  },
  {
    id: 'plan-aug-wave',
    name: 'Августовская волна',
    goal: 'maximize_margin',
    status: 'completed',
    createdBy: CURRENT_USER,
    createdAt: '2026-08-01T08:30:00',
    durationSeconds: 701,
    fieldIds: ['field-7', 'field-8', 'field-12'],
    fieldsCount: 3,
    totalArea: 1957.8,
    crops: ['Соя', 'Рапс', 'Кукуруза'],
    constraints: { budgetLimit: 14_000_000, minAreaPerCrop: 60 },
    logs: [{ timestamp: '2026-08-01T08:41:41', message: 'Расчёт завершён' }],
  },
  {
    id: 'plan-aug-retry',
    name: 'Повтор после ошибки',
    goal: 'maximize_margin',
    status: 'draft',
    createdBy: AGRONOMIST,
    createdAt: '2026-08-05T17:22:00',
    fieldIds: ['field-3'],
    fieldsCount: 1,
    totalArea: 72.4,
    crops: ['Кукуруза'],
    constraints: { budgetLimit: 1_200_000 },
    logs: [],
  },
];
